# Generated by Django 5.1 on 2024-08-14 02:01

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('user_create', models.UUIDField()),
                ('category', models.UUIDField()),
                ('severity', models.IntegerField()),
                ('description', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user_assigned', models.UUIDField()),
                ('status', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
