# Generated by Django 5.1 on 2024-08-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0004_alter_ticket_user_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_assigned',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_create',
            field=models.IntegerField(),
        ),
    ]
