# Generated by Django 5.1 on 2024-08-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0005_alter_ticket_user_assigned_alter_ticket_user_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subcategory',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
